### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by ParikshithMohan** [lemmon/kirby-portfolio-theme#1]
After completing all the installation process and when I start the php server from the kirby-portfolio-theme-master directory i get this error on localhost page.

`Parse error: syntax error, unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in C:\xampp\htdocs\kirby-portfolio-theme-master\site\plugins\color-field\Color.php on line 7`

**Comment by lemmon** [comment]
Hi @ParikshithMohan this error was due to the compatibility with PHP 7.3 and older. This issue has been fixed with 0.4.1 update.
